export const SEED_TOOLS = [
  {
    id: "1",
    name: "ChatGPT",
    slug: "chatgpt",
    tagline: "AI assistant for writing, analysis, coding, math, and creative tasks",
    description:
      "ChatGPT is an AI-powered assistant created by OpenAI that can help with a wide range of tasks. It can write essays, emails, and stories, answer questions, analyze data, write and debug code, translate languages, and much more. It's one of the most versatile AI tools available, suitable for beginners and power users alike.",
    url: "https://chat.openai.com",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 20,
    has_free_tier: true,
    has_free_trial: false,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["GPT-4o mini access", "Limited messages", "Basic features"] },
      { name: "Plus", price: 20, interval: "month" as const, features: ["GPT-4o access", "More messages", "Image generation", "Advanced analysis", "Web browsing"] },
      { name: "Team", price: 25, interval: "month" as const, features: ["Everything in Plus", "Team workspace", "Admin tools", "Higher limits"] },
    ],
    features: ["Natural language conversations", "Code writing & debugging", "Image generation (DALL-E)", "File & image analysis", "Web browsing", "Custom GPTs", "Voice conversations", "Data analysis"],
    use_cases: ["Writing assistance", "Code generation", "Research", "Learning", "Brainstorming", "Data analysis"],
    platforms: ["web" as const, "ios" as const, "android" as const, "desktop" as const],
    integrations: ["Zapier", "Google Drive", "Microsoft 365"],
    avg_rating: 4.7,
    review_count: 1250,
    is_verified: true,
    is_featured: true,
    status: "active" as const,
    meta_title: "ChatGPT — AI Assistant for Writing, Coding, and Analysis",
    meta_description: "ChatGPT by OpenAI is a versatile AI assistant. Get help with writing, coding, analysis, and more. Free tier available.",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c1", name: "Writing & Content", slug: "writing-content", description: null, icon: "PenTool", parent_id: null, display_order: 0, tool_count: 0 },
      { id: "c4", name: "Coding & Development", slug: "coding-development", description: null, icon: "Code", parent_id: null, display_order: 3, tool_count: 0 },
    ],
  },
  {
    id: "2",
    name: "Midjourney",
    slug: "midjourney",
    tagline: "Create stunning, artistic images from text descriptions",
    description:
      "Midjourney is an AI image generation tool that creates beautiful, artistic images from text prompts. Known for its distinctive aesthetic quality, it's popular among designers, artists, and content creators. It works through Discord and produces images that range from photorealistic to highly stylized artwork.",
    url: "https://midjourney.com",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "paid" as const,
    price_starting_at: 10,
    has_free_tier: false,
    has_free_trial: false,
    pricing_details: [
      { name: "Basic", price: 10, interval: "month" as const, features: ["~200 images/month", "3 concurrent jobs", "General commercial terms"] },
      { name: "Standard", price: 30, interval: "month" as const, features: ["15h fast generation", "Unlimited relaxed", "Stealth mode"] },
      { name: "Pro", price: 60, interval: "month" as const, features: ["30h fast generation", "12 concurrent jobs", "Stealth mode"] },
    ],
    features: ["Text-to-image generation", "Multiple artistic styles", "High-resolution output", "Image variation & remix", "Zoom & pan controls", "Style tuning"],
    use_cases: ["Digital art creation", "Marketing visuals", "Concept art", "Social media content", "Book illustrations"],
    platforms: ["web" as const],
    integrations: ["Discord"],
    avg_rating: 4.6,
    review_count: 890,
    is_verified: true,
    is_featured: true,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c2", name: "Image & Design", slug: "image-design", description: null, icon: "Image", parent_id: null, display_order: 1, tool_count: 0 },
    ],
  },
  {
    id: "3",
    name: "Cursor",
    slug: "cursor",
    tagline: "AI-first code editor that helps you build software faster",
    description:
      "Cursor is an AI-powered code editor built on top of VS Code. It understands your entire codebase and helps you write, edit, and debug code through natural language. You can chat with your code, get intelligent autocomplete suggestions, and make large-scale edits across multiple files at once.",
    url: "https://cursor.com",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 20,
    has_free_tier: true,
    has_free_trial: true,
    pricing_details: [
      { name: "Hobby", price: 0, interval: null, features: ["2000 completions/month", "50 slow premium requests", "VS Code extension support"] },
      { name: "Pro", price: 20, interval: "month" as const, features: ["Unlimited completions", "500 fast premium requests", "Unlimited slow requests"] },
      { name: "Business", price: 40, interval: "month" as const, features: ["Everything in Pro", "Team admin", "Usage dashboard", "Privacy mode"] },
    ],
    features: ["AI code completion", "Codebase-aware chat", "Multi-file editing", "Natural language editing", "Bug detection", "Built on VS Code"],
    use_cases: ["Software development", "Code refactoring", "Bug fixing", "Learning to code", "Rapid prototyping"],
    platforms: ["desktop" as const],
    integrations: ["GitHub", "GitLab", "VS Code extensions"],
    avg_rating: 4.8,
    review_count: 540,
    is_verified: true,
    is_featured: true,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c4", name: "Coding & Development", slug: "coding-development", description: null, icon: "Code", parent_id: null, display_order: 3, tool_count: 0 },
    ],
  },
  {
    id: "4",
    name: "Canva AI",
    slug: "canva-ai",
    tagline: "Design anything with AI-powered tools built right into Canva",
    description:
      "Canva AI brings artificial intelligence directly into the popular design platform. It includes Magic Write for text generation, Magic Design for creating layouts from prompts, background removal, image generation, and more. Perfect for non-designers who need professional-quality visuals for social media, presentations, and marketing.",
    url: "https://canva.com",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 13,
    has_free_tier: true,
    has_free_trial: true,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["Basic AI features", "250,000+ templates", "5GB cloud storage"] },
      { name: "Pro", price: 13, interval: "month" as const, features: ["All AI tools", "100M+ stock assets", "1TB storage", "Brand Kit"] },
      { name: "Teams", price: 10, interval: "month" as const, features: ["Everything in Pro", "Team collaboration", "Brand controls", "Approvals workflow"] },
    ],
    features: ["Magic Design (AI layouts)", "Magic Write (text generation)", "Background remover", "AI image generation", "Text to image", "Magic Resize", "Brand Kit"],
    use_cases: ["Social media graphics", "Presentations", "Marketing materials", "Logo design", "Video editing"],
    platforms: ["web" as const, "ios" as const, "android" as const, "desktop" as const],
    integrations: ["Google Drive", "Dropbox", "Slack", "HubSpot"],
    avg_rating: 4.5,
    review_count: 980,
    is_verified: true,
    is_featured: true,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c2", name: "Image & Design", slug: "image-design", description: null, icon: "Image", parent_id: null, display_order: 1, tool_count: 0 },
      { id: "c5", name: "Marketing", slug: "marketing", description: null, icon: "Megaphone", parent_id: null, display_order: 4, tool_count: 0 },
    ],
  },
  {
    id: "5",
    name: "Grammarly",
    slug: "grammarly",
    tagline: "AI writing assistant for grammar, tone, clarity, and style",
    description:
      "Grammarly is an AI-powered writing assistant that helps you communicate more effectively. It checks grammar, spelling, punctuation, and style in real time. The AI can also rewrite sentences for clarity, adjust tone, and generate text. Works anywhere you write — email, documents, social media, and more.",
    url: "https://grammarly.com",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 12,
    has_free_tier: true,
    has_free_trial: true,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["Basic grammar & spelling", "Tone detection", "100 AI prompts/month"] },
      { name: "Premium", price: 12, interval: "month" as const, features: ["Full sentence rewriting", "Word choice improvements", "Tone adjustments", "1000 AI prompts/month"] },
      { name: "Business", price: 15, interval: "month" as const, features: ["Everything in Premium", "Brand tones", "Knowledge sharing", "Analytics dashboard"] },
    ],
    features: ["Grammar & spell check", "Tone detection", "AI text generation", "Sentence rewriting", "Plagiarism detection", "Style guide"],
    use_cases: ["Email writing", "Academic writing", "Business communication", "Content creation", "Social media posts"],
    platforms: ["web" as const, "chrome" as const, "desktop" as const, "ios" as const, "android" as const],
    integrations: ["Gmail", "Google Docs", "Microsoft Word", "Slack"],
    avg_rating: 4.6,
    review_count: 1100,
    is_verified: true,
    is_featured: true,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c1", name: "Writing & Content", slug: "writing-content", description: null, icon: "PenTool", parent_id: null, display_order: 0, tool_count: 0 },
    ],
  },
  {
    id: "6",
    name: "Notion AI",
    slug: "notion-ai",
    tagline: "AI-powered writing and organization built into your workspace",
    description:
      "Notion AI adds artificial intelligence capabilities directly into the Notion workspace. It can help you write, summarize, brainstorm, translate, and organize your notes and documents. It works seamlessly within your existing Notion pages, making it easy to enhance your productivity without switching apps.",
    url: "https://notion.so/product/ai",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 10,
    has_free_tier: true,
    has_free_trial: true,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["Basic Notion features", "Limited AI usage", "Personal use"] },
      { name: "Plus", price: 10, interval: "month" as const, features: ["Unlimited AI responses", "Unlimited file uploads", "30-day page history"] },
      { name: "Business", price: 18, interval: "month" as const, features: ["Everything in Plus", "SAML SSO", "Advanced permissions", "90-day page history"] },
    ],
    features: ["AI writing assistant", "Document summarization", "Action item extraction", "Translation", "Brainstorming", "Q&A about your docs", "Autofill tables"],
    use_cases: ["Note taking", "Project management", "Documentation", "Meeting notes", "Content writing"],
    platforms: ["web" as const, "desktop" as const, "ios" as const, "android" as const],
    integrations: ["Slack", "Google Drive", "GitHub", "Figma", "Zapier"],
    avg_rating: 4.5,
    review_count: 720,
    is_verified: true,
    is_featured: true,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c6", name: "Business & Productivity", slug: "business-productivity", description: null, icon: "Briefcase", parent_id: null, display_order: 5, tool_count: 0 },
      { id: "c1", name: "Writing & Content", slug: "writing-content", description: null, icon: "PenTool", parent_id: null, display_order: 0, tool_count: 0 },
    ],
  },
  {
    id: "7",
    name: "Jasper",
    slug: "jasper",
    tagline: "AI marketing copilot for creating on-brand content at scale",
    description:
      "Jasper is an AI content creation platform designed for marketing teams. It helps create blog posts, social media content, ad copy, emails, and more while maintaining your brand voice and style guidelines. It's particularly strong for teams that need to produce large volumes of consistent marketing content.",
    url: "https://jasper.ai",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "paid" as const,
    price_starting_at: 39,
    has_free_tier: false,
    has_free_trial: true,
    pricing_details: [
      { name: "Creator", price: 39, interval: "month" as const, features: ["1 seat", "Brand voice", "SEO mode", "Art generation"] },
      { name: "Pro", price: 59, interval: "month" as const, features: ["Up to 5 seats", "3 brand voices", "Collaboration features", "Performance analytics"] },
      { name: "Business", price: null, interval: null, features: ["Unlimited seats", "Custom AI models", "API access", "Dedicated support"] },
    ],
    features: ["Brand voice training", "50+ content templates", "SEO optimization", "AI art generation", "Marketing campaign workflows", "Team collaboration"],
    use_cases: ["Blog writing", "Ad copy", "Email marketing", "Social media content", "Product descriptions"],
    platforms: ["web" as const, "chrome" as const],
    integrations: ["Google Docs", "Zapier", "Surfer SEO", "Grammarly", "Webflow"],
    avg_rating: 4.3,
    review_count: 560,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c5", name: "Marketing", slug: "marketing", description: null, icon: "Megaphone", parent_id: null, display_order: 4, tool_count: 0 },
      { id: "c1", name: "Writing & Content", slug: "writing-content", description: null, icon: "PenTool", parent_id: null, display_order: 0, tool_count: 0 },
    ],
  },
  {
    id: "8",
    name: "Runway",
    slug: "runway",
    tagline: "AI-powered video creation and editing for creators",
    description:
      "Runway is a creative AI platform focused on video and multimedia content. It offers text-to-video generation, video editing with AI tools, image generation, and advanced editing features like motion tracking and green screen removal. Popular with filmmakers, content creators, and digital artists.",
    url: "https://runwayml.com",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 12,
    has_free_tier: true,
    has_free_trial: false,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["125 credits", "3 video projects", "720p export"] },
      { name: "Standard", price: 12, interval: "month" as const, features: ["625 credits/month", "Unlimited projects", "4K export"] },
      { name: "Pro", price: 28, interval: "month" as const, features: ["2250 credits/month", "Unlimited projects", "4K export", "Custom AI training"] },
    ],
    features: ["Text-to-video (Gen-3)", "Video editing", "Image generation", "Motion tracking", "Background removal", "Inpainting", "Frame interpolation"],
    use_cases: ["Video production", "Film pre-visualization", "Social media content", "Music videos", "Advertising"],
    platforms: ["web" as const],
    integrations: [],
    avg_rating: 4.4,
    review_count: 430,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c3", name: "Video & Audio", slug: "video-audio", description: null, icon: "Video", parent_id: null, display_order: 2, tool_count: 0 },
    ],
  },
  {
    id: "9",
    name: "Descript",
    slug: "descript",
    tagline: "All-in-one AI video and podcast editing made simple",
    description:
      "Descript makes video and podcast editing as easy as editing a document. Its AI features include automatic transcription, filler word removal, eye contact correction, green screen, and AI voice cloning. Perfect for podcasters, YouTubers, and anyone who needs to produce video or audio content quickly.",
    url: "https://descript.com",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 24,
    has_free_tier: true,
    has_free_trial: false,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["1 hour transcription", "Basic editing", "720p export"] },
      { name: "Hobbyist", price: 24, interval: "month" as const, features: ["10h transcription/month", "AI features", "4K export"] },
      { name: "Pro", price: 33, interval: "month" as const, features: ["30h transcription/month", "All AI features", "4K export", "Priority support"] },
    ],
    features: ["Text-based video editing", "AI transcription", "Filler word removal", "Eye contact correction", "AI voice cloning", "Screen recording", "Green screen"],
    use_cases: ["Podcast editing", "YouTube videos", "Course creation", "Meeting recordings", "Social clips"],
    platforms: ["web" as const, "desktop" as const],
    integrations: ["YouTube", "Dropbox", "Google Drive"],
    avg_rating: 4.5,
    review_count: 380,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c3", name: "Video & Audio", slug: "video-audio", description: null, icon: "Video", parent_id: null, display_order: 2, tool_count: 0 },
    ],
  },
  {
    id: "10",
    name: "Copy.ai",
    slug: "copy-ai",
    tagline: "AI-powered copywriting for marketing teams and businesses",
    description:
      "Copy.ai helps marketing teams generate high-quality copy for various channels. It offers pre-built workflows for blog posts, emails, social media, product descriptions, and more. Its AI understands context and brand voice to create content that converts.",
    url: "https://copy.ai",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 36,
    has_free_tier: true,
    has_free_trial: false,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["2,000 words/month", "90+ copywriting tools", "1 user"] },
      { name: "Starter", price: 36, interval: "month" as const, features: ["Unlimited words", "Brand voices", "Blog post wizard", "5 users"] },
      { name: "Advanced", price: 186, interval: "month" as const, features: ["Everything in Starter", "Workflow automation", "API access", "Unlimited users"] },
    ],
    features: ["90+ content templates", "Blog post wizard", "Brand voice training", "Workflow automation", "Bulk content generation", "Infobase knowledge"],
    use_cases: ["Ad copy", "Blog posts", "Email campaigns", "Product descriptions", "Social media"],
    platforms: ["web" as const],
    integrations: ["Zapier", "HubSpot", "Salesforce"],
    avg_rating: 4.2,
    review_count: 410,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c5", name: "Marketing", slug: "marketing", description: null, icon: "Megaphone", parent_id: null, display_order: 4, tool_count: 0 },
      { id: "c1", name: "Writing & Content", slug: "writing-content", description: null, icon: "PenTool", parent_id: null, display_order: 0, tool_count: 0 },
    ],
  },
  {
    id: "11",
    name: "GitHub Copilot",
    slug: "github-copilot",
    tagline: "AI pair programmer that helps you write code in your editor",
    description:
      "GitHub Copilot is an AI coding assistant that integrates directly into your code editor. It suggests code completions, writes entire functions, generates tests, and helps with documentation. Trained on billions of lines of code, it supports virtually every programming language and framework.",
    url: "https://github.com/features/copilot",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 10,
    has_free_tier: true,
    has_free_trial: true,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["2,000 completions/month", "50 chat messages/month", "VS Code & CLI"] },
      { name: "Pro", price: 10, interval: "month" as const, features: ["Unlimited completions", "Unlimited chat", "All IDEs supported"] },
      { name: "Business", price: 19, interval: "month" as const, features: ["Everything in Pro", "Organization policies", "IP indemnity", "Usage metrics"] },
    ],
    features: ["Code completion", "Chat assistant", "Multi-file editing", "Test generation", "Documentation writing", "CLI integration"],
    use_cases: ["Software development", "Code review", "Test writing", "Learning new languages", "Boilerplate generation"],
    platforms: ["vscode" as const, "desktop" as const],
    integrations: ["VS Code", "JetBrains", "Neovim", "GitHub"],
    avg_rating: 4.5,
    review_count: 870,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c4", name: "Coding & Development", slug: "coding-development", description: null, icon: "Code", parent_id: null, display_order: 3, tool_count: 0 },
    ],
  },
  {
    id: "12",
    name: "ElevenLabs",
    slug: "elevenlabs",
    tagline: "AI voice generation and text-to-speech with natural human-like voices",
    description:
      "ElevenLabs creates incredibly realistic AI voices for text-to-speech, voice cloning, and dubbing. It supports 29 languages and offers tools for audiobook creation, voiceover for videos, and real-time voice conversion. The voice quality is among the best in the industry.",
    url: "https://elevenlabs.io",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 5,
    has_free_tier: true,
    has_free_trial: false,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["10,000 characters/month", "3 custom voices", "Standard voices"] },
      { name: "Starter", price: 5, interval: "month" as const, features: ["30,000 characters/month", "10 custom voices", "Commercial license"] },
      { name: "Scale", price: 99, interval: "month" as const, features: ["2M characters/month", "Unlimited voices", "44.1kHz audio", "Priority support"] },
    ],
    features: ["Text-to-speech", "Voice cloning", "29 languages", "Voice library", "Audio dubbing", "API access", "Real-time streaming"],
    use_cases: ["Audiobook narration", "Video voiceover", "Podcast production", "Accessibility", "Gaming dialogue"],
    platforms: ["web" as const, "api" as const],
    integrations: ["API", "Zapier"],
    avg_rating: 4.7,
    review_count: 450,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c3", name: "Video & Audio", slug: "video-audio", description: null, icon: "Video", parent_id: null, display_order: 2, tool_count: 0 },
    ],
  },
  {
    id: "13",
    name: "Perplexity",
    slug: "perplexity",
    tagline: "AI-powered search engine that gives cited, accurate answers",
    description:
      "Perplexity is an AI search engine that provides direct, sourced answers to your questions instead of just links. It cites its sources so you can verify information, and offers follow-up questions to dive deeper. Great for research, fact-checking, and getting quick answers to complex questions.",
    url: "https://perplexity.ai",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 20,
    has_free_tier: true,
    has_free_trial: false,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["Unlimited quick searches", "5 Pro searches/day", "Standard AI model"] },
      { name: "Pro", price: 20, interval: "month" as const, features: ["600+ Pro searches/day", "Advanced AI models", "File analysis", "API access"] },
    ],
    features: ["Cited AI answers", "Follow-up questions", "File analysis", "Image understanding", "Academic sources", "Multiple AI models"],
    use_cases: ["Research", "Fact checking", "Academic study", "Market research", "General knowledge"],
    platforms: ["web" as const, "ios" as const, "android" as const, "chrome" as const],
    integrations: [],
    avg_rating: 4.6,
    review_count: 650,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c7", name: "Education & Research", slug: "education-research", description: null, icon: "GraduationCap", parent_id: null, display_order: 6, tool_count: 0 },
    ],
  },
  {
    id: "14",
    name: "Otter.ai",
    slug: "otter-ai",
    tagline: "AI meeting assistant that transcribes and summarizes meetings",
    description:
      "Otter.ai is an AI meeting assistant that automatically joins your meetings, records, transcribes, and summarizes them. It captures action items, key decisions, and can answer questions about what was discussed. Works with Zoom, Google Meet, and Microsoft Teams.",
    url: "https://otter.ai",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 17,
    has_free_tier: true,
    has_free_trial: true,
    pricing_details: [
      { name: "Basic", price: 0, interval: null, features: ["300 minutes/month", "30 min per conversation", "Otter AI Chat"] },
      { name: "Pro", price: 17, interval: "month" as const, features: ["1200 minutes/month", "90 min per conversation", "Advanced search", "Custom vocabulary"] },
      { name: "Business", price: 30, interval: "month" as const, features: ["6000 minutes/month", "4 hour per conversation", "Admin features", "Priority support"] },
    ],
    features: ["Meeting transcription", "AI meeting summaries", "Action item extraction", "Speaker identification", "Keyword search", "Shared meeting notes"],
    use_cases: ["Meeting notes", "Interview transcription", "Lecture capture", "Sales calls", "Team collaboration"],
    platforms: ["web" as const, "ios" as const, "android" as const],
    integrations: ["Zoom", "Google Meet", "Microsoft Teams", "Slack", "Google Calendar"],
    avg_rating: 4.3,
    review_count: 390,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c6", name: "Business & Productivity", slug: "business-productivity", description: null, icon: "Briefcase", parent_id: null, display_order: 5, tool_count: 0 },
    ],
  },
  {
    id: "15",
    name: "DALL-E 3",
    slug: "dall-e-3",
    tagline: "Generate images from text descriptions with advanced AI by OpenAI",
    description:
      "DALL-E 3 is OpenAI's latest image generation model, available through ChatGPT and the API. It excels at understanding nuanced prompts, including text rendering in images, and produces high-quality, detailed images. It's one of the most accurate text-to-image models for following complex instructions.",
    url: "https://openai.com/dall-e-3",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 20,
    has_free_tier: true,
    has_free_trial: false,
    pricing_details: [
      { name: "Free (via ChatGPT)", price: 0, interval: null, features: ["Limited generations", "Via ChatGPT Free tier"] },
      { name: "ChatGPT Plus", price: 20, interval: "month" as const, features: ["More generations", "Higher resolution", "DALL-E 3 in ChatGPT"] },
      { name: "API", price: null, interval: null, features: ["Pay per image", "$0.04-$0.12 per image", "Programmatic access"] },
    ],
    features: ["Text-to-image generation", "Text in images", "High accuracy to prompts", "Multiple styles", "Inpainting", "Variations"],
    use_cases: ["Marketing visuals", "Social media content", "Product mockups", "Art creation", "Illustrations"],
    platforms: ["web" as const, "api" as const],
    integrations: ["ChatGPT", "Microsoft Bing", "API"],
    avg_rating: 4.4,
    review_count: 520,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c2", name: "Image & Design", slug: "image-design", description: null, icon: "Image", parent_id: null, display_order: 1, tool_count: 0 },
    ],
  },
  {
    id: "16",
    name: "Claude",
    slug: "claude",
    tagline: "AI assistant by Anthropic, excels at analysis, writing, and coding",
    description:
      "Claude is an AI assistant built by Anthropic that's known for being helpful, harmless, and honest. It excels at long-form writing, detailed analysis, code generation, and complex reasoning. Claude can handle very long documents and conversations, making it ideal for in-depth work.",
    url: "https://claude.ai",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 20,
    has_free_tier: true,
    has_free_trial: false,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["Basic access", "Standard usage limits", "Web interface"] },
      { name: "Pro", price: 20, interval: "month" as const, features: ["5x more usage", "Priority access", "Claude 4 family models", "Projects feature"] },
      { name: "Team", price: 25, interval: "month" as const, features: ["Everything in Pro", "Team management", "Higher limits", "Admin console"] },
    ],
    features: ["Long context window", "Document analysis", "Code generation", "Creative writing", "Reasoning", "Image understanding", "Artifacts"],
    use_cases: ["Writing", "Analysis", "Coding", "Research", "Summarization", "Tutoring"],
    platforms: ["web" as const, "ios" as const, "android" as const, "api" as const],
    integrations: ["API", "Zapier", "Amazon Bedrock"],
    avg_rating: 4.7,
    review_count: 680,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c1", name: "Writing & Content", slug: "writing-content", description: null, icon: "PenTool", parent_id: null, display_order: 0, tool_count: 0 },
      { id: "c4", name: "Coding & Development", slug: "coding-development", description: null, icon: "Code", parent_id: null, display_order: 3, tool_count: 0 },
    ],
  },
  {
    id: "17",
    name: "Synthesia",
    slug: "synthesia",
    tagline: "Create professional AI videos with virtual presenters",
    description:
      "Synthesia lets you create professional videos with AI-generated presenters — no camera, studio, or actors needed. Choose from 150+ diverse avatars or create your own, type your script, and get a polished video in minutes. Used for training, marketing, and corporate communications.",
    url: "https://synthesia.io",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "paid" as const,
    price_starting_at: 22,
    has_free_tier: false,
    has_free_trial: true,
    pricing_details: [
      { name: "Starter", price: 22, interval: "month" as const, features: ["10 min video/month", "70+ AI avatars", "120+ languages"] },
      { name: "Creator", price: 67, interval: "month" as const, features: ["30 min video/month", "90+ avatars", "Custom avatar"] },
      { name: "Enterprise", price: null, interval: null, features: ["Unlimited videos", "Custom avatars", "API access", "SSO"] },
    ],
    features: ["150+ AI avatars", "120+ languages", "Custom avatar creation", "Screen recording", "AI script assistant", "Brand kit"],
    use_cases: ["Training videos", "Marketing videos", "Product demos", "HR onboarding", "Sales enablement"],
    platforms: ["web" as const],
    integrations: ["PowerPoint", "Google Slides", "LMS platforms"],
    avg_rating: 4.3,
    review_count: 310,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c3", name: "Video & Audio", slug: "video-audio", description: null, icon: "Video", parent_id: null, display_order: 2, tool_count: 0 },
      { id: "c5", name: "Marketing", slug: "marketing", description: null, icon: "Megaphone", parent_id: null, display_order: 4, tool_count: 0 },
    ],
  },
  {
    id: "18",
    name: "Intercom Fin",
    slug: "intercom-fin",
    tagline: "AI customer support agent that resolves issues automatically",
    description:
      "Intercom Fin is an AI-powered customer support agent that can answer customer questions, resolve issues, and triage conversations automatically. It learns from your help center articles and past conversations to provide accurate, helpful responses in your brand's voice.",
    url: "https://intercom.com/fin",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "paid" as const,
    price_starting_at: 29,
    has_free_tier: false,
    has_free_trial: true,
    pricing_details: [
      { name: "Essential", price: 29, interval: "month" as const, features: ["Fin AI Agent", "Shared inbox", "Basic automation", "$0.99/resolution"] },
      { name: "Advanced", price: 85, interval: "month" as const, features: ["Everything in Essential", "Multiple inboxes", "Workflows", "Custom reports"] },
      { name: "Expert", price: 132, interval: "month" as const, features: ["Everything in Advanced", "Workload management", "Custom roles", "SSO & HIPAA"] },
    ],
    features: ["AI-powered responses", "Knowledge base integration", "Conversation routing", "Multilingual support", "Custom AI answers", "Resolution tracking"],
    use_cases: ["Customer support", "Help desk", "Live chat", "Customer onboarding", "FAQ automation"],
    platforms: ["web" as const, "ios" as const, "android" as const],
    integrations: ["Slack", "Salesforce", "HubSpot", "Jira", "Stripe"],
    avg_rating: 4.2,
    review_count: 280,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c9", name: "Customer Support", slug: "customer-support", description: null, icon: "Headphones", parent_id: null, display_order: 8, tool_count: 0 },
    ],
  },
  {
    id: "19",
    name: "Duolingo Max",
    slug: "duolingo-max",
    tagline: "AI-powered language learning with conversation practice",
    description:
      "Duolingo Max adds GPT-4 powered features to the popular language learning app. It includes Roleplay, where you practice real-world conversations with AI characters, and Explain My Answer, which gives detailed breakdowns of why answers are right or wrong. Makes language learning more interactive and personalized.",
    url: "https://duolingo.com",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 14,
    has_free_tier: true,
    has_free_trial: true,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["Basic lessons", "Limited hearts", "Ads"] },
      { name: "Super", price: 14, interval: "month" as const, features: ["No ads", "Unlimited hearts", "Progress tracking"] },
      { name: "Max", price: 30, interval: "month" as const, features: ["Everything in Super", "AI Roleplay", "Explain My Answer", "Video calls"] },
    ],
    features: ["AI conversation practice", "Personalized explanations", "40+ languages", "Gamified learning", "Speech recognition", "Streak tracking"],
    use_cases: ["Language learning", "Conversation practice", "Grammar study", "Vocabulary building"],
    platforms: ["ios" as const, "android" as const, "web" as const],
    integrations: [],
    avg_rating: 4.5,
    review_count: 920,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c7", name: "Education & Research", slug: "education-research", description: null, icon: "GraduationCap", parent_id: null, display_order: 6, tool_count: 0 },
    ],
  },
  {
    id: "20",
    name: "Gemini",
    slug: "gemini",
    tagline: "Google's AI assistant with deep integration into Google Workspace",
    description:
      "Gemini is Google's AI assistant that integrates deeply with Google Workspace apps like Gmail, Docs, Sheets, and Slides. It can draft emails, create documents, analyze spreadsheets, and generate presentations. It also works as a standalone AI chat and search tool.",
    url: "https://gemini.google.com",
    logo_url: null,
    screenshot_url: null,
    pricing_model: "freemium" as const,
    price_starting_at: 20,
    has_free_tier: true,
    has_free_trial: true,
    pricing_details: [
      { name: "Free", price: 0, interval: null, features: ["Gemini chat", "Basic features", "Google integration"] },
      { name: "Advanced", price: 20, interval: "month" as const, features: ["Gemini Advanced model", "2TB Google storage", "Gems (custom AIs)", "Google Workspace integration"] },
    ],
    features: ["Google Workspace integration", "Multimodal understanding", "Code generation", "Image understanding", "Research assistance", "Custom Gems"],
    use_cases: ["Email drafting", "Document creation", "Data analysis", "Research", "Presentation making"],
    platforms: ["web" as const, "ios" as const, "android" as const],
    integrations: ["Gmail", "Google Docs", "Google Sheets", "Google Slides", "Google Drive"],
    avg_rating: 4.3,
    review_count: 580,
    is_verified: true,
    is_featured: false,
    status: "active" as const,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
    last_verified_at: "2024-12-01T00:00:00Z",
    categories: [
      { id: "c6", name: "Business & Productivity", slug: "business-productivity", description: null, icon: "Briefcase", parent_id: null, display_order: 5, tool_count: 0 },
      { id: "c1", name: "Writing & Content", slug: "writing-content", description: null, icon: "PenTool", parent_id: null, display_order: 0, tool_count: 0 },
    ],
  },
];
